//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowsy.Db.Cli.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flowsy.Db.Cli.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HostOrIpAddress {
            get {
                return ResourceManager.GetString("HostOrIpAddress", resourceCulture);
            }
        }
        
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        internal static string ConfigurationSource {
            get {
                return ResourceManager.GetString("ConfigurationSource", resourceCulture);
            }
        }
        
        internal static string ConfigurationSourceEnvironment {
            get {
                return ResourceManager.GetString("ConfigurationSourceEnvironment", resourceCulture);
            }
        }
        
        internal static string ConfigurationSourceManual {
            get {
                return ResourceManager.GetString("ConfigurationSourceManual", resourceCulture);
            }
        }
        
        internal static string ConfigurationSectionName {
            get {
                return ResourceManager.GetString("ConfigurationSectionName", resourceCulture);
            }
        }
        
        internal static string ConfigurationNumberX {
            get {
                return ResourceManager.GetString("ConfigurationNumberX", resourceCulture);
            }
        }
        
        internal static string ConfigureAnotherConnection {
            get {
                return ResourceManager.GetString("ConfigureAnotherConnection", resourceCulture);
            }
        }
        
        internal static string ProviderInvariantName {
            get {
                return ResourceManager.GetString("ProviderInvariantName", resourceCulture);
            }
        }
        
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string AdditionalOptions {
            get {
                return ResourceManager.GetString("AdditionalOptions", resourceCulture);
            }
        }
        
        internal static string DatabaseProviderXIsNotSupported {
            get {
                return ResourceManager.GetString("DatabaseProviderXIsNotSupported", resourceCulture);
            }
        }
        
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        internal static string EnterConnectionKey {
            get {
                return ResourceManager.GetString("EnterConnectionKey", resourceCulture);
            }
        }
        
        internal static string BooleanAnswerYesShort {
            get {
                return ResourceManager.GetString("BooleanAnswerYesShort", resourceCulture);
            }
        }
        
        internal static string BooleanAnswerYesLong {
            get {
                return ResourceManager.GetString("BooleanAnswerYesLong", resourceCulture);
            }
        }
        
        internal static string BooleanAnswerNoShort {
            get {
                return ResourceManager.GetString("BooleanAnswerNoShort", resourceCulture);
            }
        }
        
        internal static string BooleanAnswerNoLong {
            get {
                return ResourceManager.GetString("BooleanAnswerNoLong", resourceCulture);
            }
        }
        
        internal static string ConfigureMigrations {
            get {
                return ResourceManager.GetString("ConfigureMigrations", resourceCulture);
            }
        }
        
        internal static string DirectoryContainigMigrationScripts {
            get {
                return ResourceManager.GetString("DirectoryContainigMigrationScripts", resourceCulture);
            }
        }
        
        internal static string SchemaContainingMigrationMetadata {
            get {
                return ResourceManager.GetString("SchemaContainingMigrationMetadata", resourceCulture);
            }
        }
        
        internal static string TableContainingMigrationMetadata {
            get {
                return ResourceManager.GetString("TableContainingMigrationMetadata", resourceCulture);
            }
        }
        
        internal static string SqlStatementToBeExecutedAfterMigrations {
            get {
                return ResourceManager.GetString("SqlStatementToBeExecutedAfterMigrations", resourceCulture);
            }
        }
        
        internal static string ChooseDatabaseOperation {
            get {
                return ResourceManager.GetString("ChooseDatabaseOperation", resourceCulture);
            }
        }
        
        internal static string RunMigrations {
            get {
                return ResourceManager.GetString("RunMigrations", resourceCulture);
            }
        }
        
        internal static string NoConfigurationWasProvided {
            get {
                return ResourceManager.GetString("NoConfigurationWasProvided", resourceCulture);
            }
        }
    }
}
